name: Bug Report
description: File a bug report
title: "[Bug]: "
labels:
  - "bug"
assignees:
  - siriusu
body:
  - type: textarea
    attributes:
      label: バグの詳細
      description: 発生したバグの詳細
      placeholder: どんなバグが発生したのか
    validations:
      required: true
  - type: textarea
    attributes:
      label: 関連するログ
      description: 発生したバグに関連するログを添付する
      render: Shell